export const metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="mb-2 text-4xl font-extrabold">Terms of Service</h1>
      <p className="mb-10 text-sm text-white/40">
        Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
      </p>

      <div className="prose prose-invert prose-sm max-w-none space-y-8 text-white/70">
        <section>
          <h2 className="mb-3 text-xl font-bold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Epic Music Space (&quot;EMS,&quot; &quot;the Platform,&quot; &quot;we,&quot; &quot;us&quot;) you
            agree to be bound by these Terms of Service and all applicable laws and
            regulations. If you do not agree, do not use the Platform.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">2. Nature of the Platform</h2>
          <p>
            Epic Music Space is a <strong className="text-white">digital music licensing and revenue
            participation platform</strong>. The Platform facilitates the sale of digital
            content licenses that grant holders a contractual right to a defined
            portion of the streaming revenue generated by specific musical works.
          </p>
          <p className="mt-3">
            <strong className="text-white">Licenses are not securities.</strong> Licenses offered on EMS are
            digital content licenses, not investment contracts, securities,
            equity interests, or debt instruments of any kind. The purchase of a
            license does not represent an investment in EMS, in any artist, or in
            any entity. EMS does not register or intend to register any license as
            a security under the Securities Act of 1933 or any applicable state
            or foreign law.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">3. Eligibility</h2>
          <p>
            You must be at least 18 years old and have the legal capacity to enter
            into contracts. By creating an account you represent that you meet these
            requirements.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">4. User Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account
            credentials and for all activity that occurs under your account. You
            agree to notify us immediately of any unauthorized use.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">5. Artist Obligations</h2>
          <p>
            Artists who upload music to EMS represent and warrant that: (a) they
            own or control all rights necessary to license the music; (b) the music
            does not infringe any third-party intellectual property rights; (c) they
            will fulfill their revenue-share obligations to license holders as set
            out in the applicable Licensing Agreement.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">6. Payments &amp; Fees</h2>
          <p>
            All payments are processed by Stripe. EMS retains a platform fee
            (disclosed at checkout) from each license sale. Streaming revenue
            payouts to license holders are made quarterly, subject to a minimum
            payout threshold.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">7. No Guarantees</h2>
          <p>
            EMS makes no guarantee of revenue. Streaming revenue is inherently
            variable and may be zero. Past performance does not guarantee future
            earnings.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, EMS shall not be liable for
            any indirect, incidental, special, or consequential damages arising
            from use of the Platform.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">9. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware, USA,
            without regard to its conflict of law provisions.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">10. Changes to Terms</h2>
          <p>
            We may update these Terms at any time. We will notify you of material
            changes by email or by posting a notice on the Platform. Continued use
            after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">11. Records &amp; Audit Trails</h2>
          <p>
            For licensing and auction activity, EMS stores transaction and bidding
            records for compliance, fraud prevention, and dispute handling.
            Participants in an auction (seller, winner, bidders) may export
            their auction records in machine-readable formats from the relevant
            auction page.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">12. User Content &amp; Content License to EMS</h2>
          <p>
            When you upload, post, or otherwise submit any audio, artwork, text, metadata, or
            other content (&ldquo;User Content&rdquo;) to the Platform, you represent and warrant that:
          </p>
          <ul className="mt-3 list-disc space-y-1 pl-5 text-sm">
            <li>You own or have obtained all necessary rights, licenses, consents, and permissions to upload, reproduce, distribute, and publicly perform the User Content on the Platform.</li>
            <li>The User Content does not infringe any third-party intellectual property rights, including copyrights, trademarks, trade secrets, or moral rights.</li>
            <li>No sample, loop, sound kit element, or recording embedded in the User Content was taken from a copyrighted source without an appropriate commercial license.</li>
            <li>The User Content does not violate any applicable law or regulation.</li>
          </ul>
          <p className="mt-3 text-sm">
            By submitting User Content you grant Epic Music Space, LLC a worldwide, non-exclusive,
            royalty-free, sublicensable license to host, cache, display, distribute, and promote
            the User Content solely as necessary to operate and market the Platform (including
            embedding previews in social-media cards, Stories, and third-party embeds that you
            explicitly trigger). This license terminates when you delete the User Content from
            the Platform, except as needed to wind down distributed copies or comply with legal
            obligations.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">13. User Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless Epic Music Space, LLC, its
            officers, directors, employees, and agents from and against any claims, damages,
            obligations, losses, liabilities, costs, and expenses (including reasonable
            attorneys&apos; fees) arising out of or related to: (a) your User Content;
            (b) your use or misuse of the Platform; (c) your violation of these Terms;
            or (d) your violation of any third-party right, including any intellectual property
            or privacy right.
          </p>
          <p className="mt-3 text-sm">
            EMS reserves the right to assume the exclusive defense and control of any matter
            subject to indemnification by you, and you agree to cooperate with EMS in asserting
            any available defenses.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">14. DMCA Safe Harbor &amp; Takedown</h2>
          <p>
            EMS complies with the Digital Millennium Copyright Act (17 U.S.C. § 512). If you
            believe content on the Platform infringes your copyright, submit a takedown notice
            to our Designated Agent at{" "}
            <a href="mailto:dmca@epicmusicspace.com" className="text-brand-400 hover:underline">
              dmca@epicmusicspace.com
            </a>{" "}
            as described on our{" "}
            <a href="/dmca" className="text-brand-400 hover:underline">DMCA Policy page</a>.
            Repeat infringers will have their accounts terminated.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">15. Contact</h2>
          <p>
            Questions about these Terms? Contact us at{" "}
            <a href="mailto:legal@epicmusicspace.com" className="text-brand-400 hover:underline">
              legal@epicmusicspace.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
