"use client";
import Link from "next/link";
import type { StudioEditMode, StudioExperienceMode, StudioMode, StudioTask, StudioTool } from "../types";
import { formatTimelineTime } from "../timeline";
import { getStudioModeLabel, getStudioSaveTone } from "../presentation";
import { getStudioCommandIds, getStudioTasks } from "../workspace";
import { ProjectMenu } from "./ProjectMenu";
import { StudioModeSwitch } from "./StudioModeSwitch";
import { ProjectHealth } from "./ProjectHealth";
import { StudioIcon, type StudioIconName } from "./StudioIcon";
import type { StudioSaveState } from "../recovery";

const modes: Array<{ id: StudioMode; icon: StudioIconName }> = [{ id:"edit",icon:"timeline" },{ id:"mix",icon:"mixer" },{ id:"beat",icon:"beat" },{ id:"export",icon:"archive" },{ id:"files",icon:"files" }];
type Props = { mode:StudioMode; setMode:(v:StudioMode)=>void; experience:StudioExperienceMode; setExperience:(v:StudioExperienceMode)=>void; task:StudioTask; setTask:(v:StudioTask)=>void; title:string; setTitle:(v:string)=>void; saveStatus:string; saveState:StudioSaveState; savedAt?:string; missingMedia:number; dirty:boolean; busy:boolean; playing:boolean; recording:boolean; tracksLength:number; playhead:number; onNew:()=>void; onSave:()=>void; onSaveAs:()=>void; onRestore:()=>void; onSnapshot:()=>void; onArchive:()=>void; onStop:(reset?:boolean)=>void; onPlay:()=>void; onRecord:()=>void; onImport:(files:FileList)=>void; undo:()=>void; redo:()=>void; tool:StudioTool; setTool:(v:StudioTool)=>void; editMode:StudioEditMode; setEditMode:(v:StudioEditMode)=>void; zoomOut:()=>void; zoomIn:()=>void; fit:()=>void; bpm:number; setBpm:(v:number)=>void; sampleRate:number; setSampleRate:(v:number)=>void; nudge:number; setNudge:(v:number)=>void; grid:number; setGrid:(v:number)=>void };

export function StudioChrome(props: Props) {
  const { mode,setMode,experience,setExperience,task,setTask,title,setTitle,saveStatus,saveState,savedAt,missingMedia,dirty,busy,playing,recording,tracksLength,playhead,onNew,onSave,onSaveAs,onRestore,onSnapshot,onArchive,onStop,onPlay,onRecord,onImport,undo,redo,tool,setTool,editMode,setEditMode,zoomOut,zoomIn,fit,bpm,setBpm,sampleRate,setSampleRate,nudge,setNudge,grid,setGrid }=props;
  const saveTone=getStudioSaveTone(saveStatus); const commandIds=getStudioCommandIds(experience,task,tracksLength>0); const precision=commandIds.includes("precision-tools");
  return <header className="studio-command">
    <div className="studio-command__top">
      <div className="studio-brand-zone"><Link href="/" className="studio-exit" aria-label="Back to Epic Music Space">←</Link><button type="button" className="studio-brand" onClick={()=>setMode("edit")} aria-label="Open Studio timeline"><span className="studio-brand__mark"><StudioIcon name="spark"/></span><span><b>EPIC</b><small>PLATINUM STUDIO</small></span></button></div>
      {experience==="creator"?<nav className="studio-tasks" aria-label="Creator workflow">{getStudioTasks().map(item=><button key={item.id} onClick={()=>setTask(item.id)} className={task===item.id?"is-active":""} aria-current={task===item.id?"step":undefined}>{item.label}</button>)}</nav>:<nav className="studio-modes" aria-label="Studio workspaces">{modes.map(({id,icon})=><button key={id} onClick={()=>setMode(id)} className={mode===id?"is-active":""} aria-current={mode===id?"page":undefined}><StudioIcon name={icon}/><span>{getStudioModeLabel(id)}</span></button>)}</nav>}
      <div className="studio-session"><span className="studio-session__eyebrow">CURRENT SESSION</span><input aria-label="Session title" value={title} onChange={e=>setTitle(e.target.value)}/><ProjectHealth missingMedia={missingMedia} clipping={false} saveState={dirty&&saveState==="cloud-saved"?"local-draft":saveState} savedAt={savedAt}/><span className={`studio-save studio-save--${saveTone.tone} sr-only`}>{saveStatus}</span></div>
      <div className="studio-counter"><small>PLAYHEAD</small><strong>{formatTimelineTime(playhead)}</strong></div>
    </div>
    <div className="studio-command__controls">
      <div className="studio-command__identity"><ProjectMenu onNew={onNew} onSaveAs={onSaveAs} onRestore={onRestore} onSnapshot={onSnapshot} onArchive={onArchive}/><button className="studio-save-now" onClick={onSave} disabled={busy}><StudioIcon name="save"/> {busy?"Working":"Save"}</button></div>
      <div className="studio-transport"><button aria-label="Return to start" onClick={()=>onStop(true)}><span className="studio-return">|‹</span></button><button aria-label="Stop" onClick={()=>onStop()}><StudioIcon name="stop"/></button><button className={`studio-play ${playing?"is-playing":""}`} aria-label={playing?"Pause":"Play"} onClick={onPlay} disabled={!tracksLength}><StudioIcon name={playing?"pause":"play"}/></button><button className={`studio-record ${recording?"is-recording":""}`} aria-label={recording?"Stop recording":"Record"} onClick={onRecord}><StudioIcon name="record"/></button></div>
      {commandIds.includes("import")&&<label className="studio-import"><StudioIcon name="import"/><span>{busy?"WORKING":"IMPORT"}</span><input type="file" accept="audio/*,.wav,.wave,.mp3,.m4a,.aac,.ogg,.oga,.webm,.flac,.aif,.aiff,.mp4" multiple className="sr-only" onChange={e=>e.target.files&&onImport(e.target.files)}/></label>}
      {commandIds.includes("undo-redo")&&<div className="studio-tools"><button aria-label="Undo" onClick={undo}><StudioIcon name="undo"/></button><button aria-label="Redo" onClick={redo}><StudioIcon name="undo" className="rotate-180"/></button>{commandIds.includes("zoom")&&<><button aria-label="Zoom out" onClick={zoomOut}><StudioIcon name="zoomOut"/></button><button aria-label="Zoom in" onClick={zoomIn}><StudioIcon name="zoomIn"/></button><button onClick={fit}>FIT</button></>}</div>}
      {precision&&<div className="studio-selects"><label>TOOL<select value={tool} onChange={e=>setTool(e.target.value as StudioTool)}>{["smart","selector","grabber","trim","pencil","scrubber","zoomer"].map(item=><option key={item}>{item}</option>)}</select></label><label>MODE<select value={editMode} onChange={e=>setEditMode(e.target.value as StudioEditMode)}>{["slip","grid","spot","shuffle"].map(item=><option key={item}>{item}</option>)}</select></label><label>NUDGE<select value={nudge} onChange={e=>setNudge(Number(e.target.value))}><option value={.01}>10MS</option><option value={.05}>50MS</option><option value={.1}>100MS</option><option value={.25}>250MS</option><option value={1}>1S</option></select></label><label>GRID<select value={grid} onChange={e=>setGrid(Number(e.target.value))}><option value={.125}>1/8</option><option value={.25}>1/4</option><option value={.5}>1/2</option><option value={1}>1S</option></select></label><label>BPM<input value={bpm} inputMode="numeric" onChange={e=>setBpm(Number(e.target.value)||92)}/></label><label>RATE<select value={sampleRate} onChange={e=>setSampleRate(Number(e.target.value))}><option value={44100}>44.1K</option><option value={48000}>48K</option><option value={96000}>96K</option></select></label></div>}
      <div className="studio-command__utility"><StudioModeSwitch value={experience} onChange={setExperience}/><Link href="/support?topic=studio" className="studio-help" title="Studio help">?</Link></div>
    </div>
  </header>;
}
