/**
 * Type-cast helpers for Supabase joined queries.
 *
 * Supabase SDK v2 requires `Relationships` metadata on table types to infer
 * joined select results. Until those are generated by `supabase gen types`,
 * we use explicit cast helpers so the rest of the codebase stays clean.
 */
import { createClient as createBrowserClient } from "@/lib/supabase/client";
import { SongWithArtist, CommentWithUser, BidWithBidder } from "@/types/database";

type SupabaseClient = ReturnType<typeof createBrowserClient>;

export async function fetchSongWithArtist(supabase: SupabaseClient, id: string) {
  const res = await (supabase
    .from("songs")
    .select("*, profiles(*)")
    .eq("id", id)
    .single() as unknown as Promise<{ data: SongWithArtist | null; error: unknown }>);
  return res;
}

export async function fetchSongsWithArtist(
  supabase: SupabaseClient,
  query: (q: ReturnType<SupabaseClient["from"]>) => ReturnType<SupabaseClient["from"]>
) {
  const base = supabase.from("songs").select("*, profiles(*)");
  const res = await (query(base as unknown as ReturnType<SupabaseClient["from"]>) as unknown as Promise<{ data: SongWithArtist[] | null; error: unknown }>);
  return res;
}

export async function fetchCommentsWithUser(supabase: SupabaseClient, songId: string) {
  const res = await (supabase
    .from("comments")
    .select("*, profiles(*)")
    .eq("song_id", songId)
    .order("created_at", { ascending: false }) as unknown as Promise<{ data: CommentWithUser[] | null; error: unknown }>);
  return res;
}

export async function fetchBidsWithBidder(supabase: SupabaseClient, songId: string) {
  const res = await (supabase
    .from("bids")
    .select("*, profiles(*)")
    .eq("song_id", songId)
    .eq("status", "active")
    .order("amount", { ascending: false }) as unknown as Promise<{ data: BidWithBidder[] | null; error: unknown }>);
  return res;
}
