import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

export const repoRoot = path.resolve(here, "..", "..");
export const vercelProjectFile = path.join(repoRoot, ".vercel", "project.json");

export function fileExists(filePath) {
  return fs.existsSync(filePath);
}

export function ensureDirectory(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

export function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

export function readText(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

export function writeText(filePath, text) {
  ensureDirectory(filePath);
  fs.writeFileSync(filePath, text, "utf8");
}

export function runCommand(command, args = [], options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd ?? repoRoot,
    encoding: options.stdio === "inherit" ? undefined : "utf8",
    input: options.input,
    env: { ...process.env, ...(options.env ?? {}) },
    stdio: options.stdio ?? "pipe",
  });

  return {
    ok: result.status === 0,
    status: result.status ?? 1,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
    error: result.error ?? null,
  };
}

export function commandExists(command) {
  const result = runCommand("sh", ["-lc", `command -v ${command}`]);
  return result.ok;
}

const npxFallbackTools = new Set(["gh", "vercel", "supabase"]);

export function canUseNpxFallback(command) {
  return npxFallbackTools.has(command);
}

export function runToolCommand(command, args = [], options = {}) {
  if (commandExists(command)) {
    return runCommand(command, args, options);
  }

  if (canUseNpxFallback(command)) {
    return runCommand("npx", ["--yes", command, ...args], options);
  }

  return runCommand(command, args, options);
}

export function fail(message, code = 1) {
  console.error(`ERROR: ${message}`);
  process.exit(code);
}

export function info(message) {
  console.log(message);
}

export function parseEnvText(text) {
  const env = {};

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const separatorIndex = line.indexOf("=");
    if (separatorIndex === -1) continue;

    const key = line.slice(0, separatorIndex).trim();
    let value = line.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    value = value
      .replace(/\\n/g, "\n")
      .replace(/\\r/g, "\r")
      .replace(/\\t/g, "\t");

    env[key] = value;
  }

  return env;
}

export function loadEnvFile(filePath) {
  if (!fileExists(filePath)) return {};
  return parseEnvText(readText(filePath));
}

export function formatEnvValue(value) {
  return `"${String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/"/g, '\\"')}"`;
}

export function writeEnvFile(filePath, keys, values, title) {
  const lines = [
    `# Generated by ${title}`,
    "# Do not edit by hand; re-run the ops command instead.",
    "",
  ];

  for (const key of keys) {
    if (!(key in values)) continue;
    if (values[key] === "") continue;
    lines.push(`${key}=${formatEnvValue(values[key])}`);
  }

  lines.push("");
  writeText(filePath, lines.join("\n"));
}

export function unique(values) {
  return [...new Set(values)];
}

export function missingKeys(values, requiredKeys) {
  return requiredKeys.filter((key) => {
    const value = values[key];
    return value === undefined || value === null || String(value).trim() === "";
  });
}

export function readVercelLink() {
  if (!fileExists(vercelProjectFile)) return null;

  try {
    return readJson(vercelProjectFile);
  } catch {
    return null;
  }
}

export function getOriginUrl() {
  const result = runCommand("git", ["remote", "get-url", "origin"]);
  if (!result.ok) return null;
  return result.stdout.trim();
}

export function deriveGitHubRepository(originUrl = getOriginUrl()) {
  if (!originUrl) return null;

  const cleaned = originUrl.trim().replace(/\.git$/, "");
  const match = cleaned.match(/github\.com[:/](.+\/.+)$/);
  return match ? match[1] : null;
}

export function deriveSupabaseProjectRef(values = {}) {
  if (values.SUPABASE_PROJECT_REF) return values.SUPABASE_PROJECT_REF;

  const url = values.NEXT_PUBLIC_SUPABASE_URL;
  if (!url) return null;

  try {
    const hostname = new URL(url).hostname;
    return hostname.split(".")[0] || null;
  } catch {
    return null;
  }
}

export function fetchDopplerSecrets(configName, options = {}) {
  const args = [
    "secrets",
    "download",
    "--no-file",
    "--format",
    "json",
    "--config",
    configName,
  ];

  if (process.env.DOPPLER_PROJECT) {
    args.push("--project", process.env.DOPPLER_PROJECT);
  }

  const result = runCommand("doppler", args);
  if (!result.ok) {
    const message = `Doppler secrets download failed for config "${configName}". ${result.stderr.trim()}`;
    if (options.throwOnError) {
      throw new Error(message);
    }
    fail(message);
  }

  try {
    return JSON.parse(result.stdout);
  } catch (error) {
    const message = `Could not parse Doppler output for config "${configName}": ${error}`;
    if (options.throwOnError) {
      throw new Error(message);
    }
    fail(message);
  }
}

export function resolveOpsMetadata(values) {
  const linked = readVercelLink();

  return {
    repository: values.GITHUB_REPOSITORY ?? deriveGitHubRepository(),
    vercelOrgId: values.VERCEL_ORG_ID ?? linked?.orgId ?? null,
    vercelProjectId: values.VERCEL_PROJECT_ID ?? linked?.projectId ?? null,
    supabaseProjectRef: deriveSupabaseProjectRef(values),
  };
}

export function summarizeStatus(label, ok, detail) {
  const prefix = ok === "warn" ? "WARN" : ok ? "PASS" : "FAIL";
  console.log(`${prefix} ${label}${detail ? ` - ${detail}` : ""}`);
}
