export const metadata = {
  title: "Licensing Agreement — Epic Music Space",
};

export default function LicensingPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="mb-2 text-4xl font-extrabold">Digital Music Licensing Agreement</h1>
      <p className="mb-4 text-sm text-white/40">
        Last updated:{" "}
        {new Date().toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })}
      </p>
      <div className="mb-10 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-400">
        <strong>Important legal notice:</strong> This agreement governs digital
        content licenses sold on Epic Music Space. These licenses are{" "}
        <strong>not securities</strong>, not investment contracts, and do not
        confer any equity or ownership interest in any artist, song, or company.
        They are contractual rights to a defined share of streaming royalties.
      </div>

      <div className="space-y-8 text-white/70">
        <section>
          <h2 className="mb-3 text-xl font-bold text-white">
            1. Parties
          </h2>
          <p className="text-sm">
            This Agreement is between Epic Music Space, LLC (&quot;EMS&quot;), the
            Artist (the party who uploaded the Song), and the License Holder
            (the party who purchased the License). By completing a license
            purchase you agree to be bound by this Agreement.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">
            2. What a License Is
          </h2>
          <p className="text-sm">
            A <strong className="text-white">Digital Music License</strong> is a
            limited, non-transferable, non-exclusive contractual right that
            entitles the License Holder to receive a pro-rata share of the
            Net Streaming Revenue generated by the specified Song during the
            License Term.
          </p>
          <ul className="mt-3 list-disc space-y-1 pl-5 text-sm">
            <li>
              The License does not convey copyright ownership, mechanical rights,
              synchronization rights, or any other intellectual property right.
            </li>
            <li>
              The License does not represent equity, debt, or any security in any
              entity.
            </li>
            <li>
              The License Holder may not reproduce, distribute, publicly perform,
              or create derivative works from the Song.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">
            3. Revenue Participation
          </h2>
          <p className="text-sm">
            The <strong className="text-white">Artist Revenue Share Percentage</strong>{" "}
            (set by the Artist at the time of listing) is divided equally among
            all licenses issued for that Song.
          </p>
          <p className="mt-3 text-sm">
            <strong className="text-white">Example:</strong> If an Artist sets a
            10% revenue share and issues 100 licenses, each license holder
            receives 10% ÷ 100 = 0.1% of Net Streaming Revenue per quarter.
          </p>
          <p className="mt-3 text-sm">
            <strong className="text-white">Net Streaming Revenue</strong> means
            gross streaming royalties received by EMS or the Artist, less
            platform fees (currently 15%) and applicable withholding taxes.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">4. Payout Schedule</h2>
          <p className="text-sm">
            Revenue payouts are made quarterly (March 31, June 30, September 30,
            December 31) for the preceding quarter, subject to a minimum payout
            of $5.00 USD. Amounts below the threshold roll over to the next
            quarter.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">5. License Term</h2>
          <p className="text-sm">
            Unless revoked for cause (see Section 7), licenses are perpetual for
            as long as the Song generates trackable streaming revenue on supported
            platforms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">
            6. No Guarantees
          </h2>
          <p className="text-sm">
            EMS and the Artist make no guarantee of streaming revenue. Revenue
            may be zero. Past streaming performance does not indicate future
            results. License Holders acknowledge they may receive no revenue
            distributions.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">
            7. Revocation
          </h2>
          <p className="text-sm">
            EMS may revoke a License with 30 days&apos; notice and a full refund of
            the original purchase price if: (a) the Song is found to infringe
            third-party rights; (b) the Artist requests delisting due to
            contractual obligations with a label; or (c) required by law.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">
            8. Non-Transferability
          </h2>
          <p className="text-sm">
            Licenses may not be sold, transferred, or assigned to third parties
            in Phase 1. Secondary market functionality may be introduced in a
            future platform version.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">
            9. Tax Obligations
          </h2>
          <p className="text-sm">
            License Holders are solely responsible for any taxes owed on revenue
            distributions received. EMS will provide a 1099 form (or equivalent)
            to U.S.-based License Holders who receive $600 or more in a calendar
            year.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">10. Governing Law</h2>
          <p className="text-sm">
            This Agreement is governed by the laws of the State of Delaware, USA.
            Disputes shall be resolved by binding arbitration under the rules of
            the American Arbitration Association.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-bold text-white">11. Contact</h2>
          <p className="text-sm">
            Legal questions:{" "}
            <a
              href="mailto:legal@epicmusicspace.com"
              className="text-brand-400 hover:underline"
            >
              legal@epicmusicspace.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
